/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as ProtectedSuscripcionRouteImport } from './routes/_protected/suscripcion'
import { Route as ProtectedPerfilRouteRouteImport } from './routes/_protected/perfil/route'
import { Route as ProtectedIluminacionIndexRouteImport } from './routes/_protected/iluminacion/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedPerfilTecnicosIndexRouteImport } from './routes/_protected/perfil/tecnicos/index'
import { Route as ProtectedPerfilInstrumentosIndexRouteImport } from './routes/_protected/perfil/instrumentos/index'
import { Route as ProtectedPerfilEmpresasIndexRouteImport } from './routes/_protected/perfil/empresas/index'
import { Route as ProtectedIluminacionReportesIndexRouteImport } from './routes/_protected/iluminacion/reportes/index'
import { Route as ProtectedIluminacionReportesChar91idChar93MenuRouteRouteImport } from './routes/_protected/iluminacion/reportes/[$id]/_menu/route'
import { Route as ProtectedIluminacionReportesPdfChar91idChar93ReducidaRouteImport } from './routes/_protected/iluminacion/reportes/pdf/[$id]/reducida'
import { Route as ProtectedIluminacionReportesPdfChar91idChar93CompletaRouteImport } from './routes/_protected/iluminacion/reportes/pdf/[$id]/completa'
import { Route as ProtectedIluminacionReportesChar91idChar93MenuResumenRouteImport } from './routes/_protected/iluminacion/reportes/[$id]/_menu/resumen'
import { Route as ProtectedIluminacionReportesChar91idChar93MenuGeneralRouteImport } from './routes/_protected/iluminacion/reportes/[$id]/_menu/general'
import { Route as ProtectedIluminacionReportesChar91idChar93MenuAreassRouteImport } from './routes/_protected/iluminacion/reportes/[$id]/_menu/areass'
import { Route as ProtectedIluminacionReportesChar91idChar93CRUDAreasIndexRouteImport } from './routes/_protected/iluminacion/reportes/[$id]/_CRUD/areas/index'
import { Route as ProtectedIluminacionReportesChar91idChar93CRUDCrudEditResumenRouteImport } from './routes/_protected/iluminacion/reportes/[$id]/_CRUD/crud.edit-resumen'
import { Route as ProtectedIluminacionReportesChar91idChar93CRUDCrudEditGeneralRouteImport } from './routes/_protected/iluminacion/reportes/[$id]/_CRUD/crud.edit-general'
import { Route as ProtectedIluminacionReportesChar91idChar93CRUDCrudCreateResumenRouteImport } from './routes/_protected/iluminacion/reportes/[$id]/_CRUD/crud.create-resumen'
import { Route as ProtectedIluminacionReportesChar91idChar93CRUDCrudCreateGeneralRouteImport } from './routes/_protected/iluminacion/reportes/[$id]/_CRUD/crud.create-general'
import { Route as ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93PuntosRouteImport } from './routes/_protected/iluminacion/reportes/[$id]/_CRUD/areas/[$areaId]/puntos'
import { Route as ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93EditAreaRouteImport } from './routes/_protected/iluminacion/reportes/[$id]/_CRUD/areas/[$areaId]/edit-area'
import { Route as ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93CreateAreaRouteImport } from './routes/_protected/iluminacion/reportes/[$id]/_CRUD/areas/[$areaId]/create-area'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSuscripcionRoute = ProtectedSuscripcionRouteImport.update({
  id: '/suscripcion',
  path: '/suscripcion',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedPerfilRouteRoute = ProtectedPerfilRouteRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedIluminacionIndexRoute =
  ProtectedIluminacionIndexRouteImport.update({
    id: '/iluminacion/',
    path: '/iluminacion/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPerfilTecnicosIndexRoute =
  ProtectedPerfilTecnicosIndexRouteImport.update({
    id: '/tecnicos/',
    path: '/tecnicos/',
    getParentRoute: () => ProtectedPerfilRouteRoute,
  } as any)
const ProtectedPerfilInstrumentosIndexRoute =
  ProtectedPerfilInstrumentosIndexRouteImport.update({
    id: '/instrumentos/',
    path: '/instrumentos/',
    getParentRoute: () => ProtectedPerfilRouteRoute,
  } as any)
const ProtectedPerfilEmpresasIndexRoute =
  ProtectedPerfilEmpresasIndexRouteImport.update({
    id: '/empresas/',
    path: '/empresas/',
    getParentRoute: () => ProtectedPerfilRouteRoute,
  } as any)
const ProtectedIluminacionReportesIndexRoute =
  ProtectedIluminacionReportesIndexRouteImport.update({
    id: '/iluminacion/reportes/',
    path: '/iluminacion/reportes/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedIluminacionReportesChar91idChar93MenuRouteRoute =
  ProtectedIluminacionReportesChar91idChar93MenuRouteRouteImport.update({
    id: '/iluminacion/reportes/$id/_menu',
    path: '/iluminacion/reportes/$id',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedIluminacionReportesPdfChar91idChar93ReducidaRoute =
  ProtectedIluminacionReportesPdfChar91idChar93ReducidaRouteImport.update({
    id: '/iluminacion/reportes/pdf/$id/reducida',
    path: '/iluminacion/reportes/pdf/$id/reducida',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedIluminacionReportesPdfChar91idChar93CompletaRoute =
  ProtectedIluminacionReportesPdfChar91idChar93CompletaRouteImport.update({
    id: '/iluminacion/reportes/pdf/$id/completa',
    path: '/iluminacion/reportes/pdf/$id/completa',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedIluminacionReportesChar91idChar93MenuResumenRoute =
  ProtectedIluminacionReportesChar91idChar93MenuResumenRouteImport.update({
    id: '/resumen',
    path: '/resumen',
    getParentRoute: () =>
      ProtectedIluminacionReportesChar91idChar93MenuRouteRoute,
  } as any)
const ProtectedIluminacionReportesChar91idChar93MenuGeneralRoute =
  ProtectedIluminacionReportesChar91idChar93MenuGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () =>
      ProtectedIluminacionReportesChar91idChar93MenuRouteRoute,
  } as any)
const ProtectedIluminacionReportesChar91idChar93MenuAreassRoute =
  ProtectedIluminacionReportesChar91idChar93MenuAreassRouteImport.update({
    id: '/areass',
    path: '/areass',
    getParentRoute: () =>
      ProtectedIluminacionReportesChar91idChar93MenuRouteRoute,
  } as any)
const ProtectedIluminacionReportesChar91idChar93CRUDAreasIndexRoute =
  ProtectedIluminacionReportesChar91idChar93CRUDAreasIndexRouteImport.update({
    id: '/iluminacion/reportes/$id/_CRUD/areas/',
    path: '/iluminacion/reportes/$id/areas/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedIluminacionReportesChar91idChar93CRUDCrudEditResumenRoute =
  ProtectedIluminacionReportesChar91idChar93CRUDCrudEditResumenRouteImport.update(
    {
      id: '/iluminacion/reportes/$id/_CRUD/crud/edit-resumen',
      path: '/iluminacion/reportes/$id/crud/edit-resumen',
      getParentRoute: () => ProtectedRouteRoute,
    } as any,
  )
const ProtectedIluminacionReportesChar91idChar93CRUDCrudEditGeneralRoute =
  ProtectedIluminacionReportesChar91idChar93CRUDCrudEditGeneralRouteImport.update(
    {
      id: '/iluminacion/reportes/$id/_CRUD/crud/edit-general',
      path: '/iluminacion/reportes/$id/crud/edit-general',
      getParentRoute: () => ProtectedRouteRoute,
    } as any,
  )
const ProtectedIluminacionReportesChar91idChar93CRUDCrudCreateResumenRoute =
  ProtectedIluminacionReportesChar91idChar93CRUDCrudCreateResumenRouteImport.update(
    {
      id: '/iluminacion/reportes/$id/_CRUD/crud/create-resumen',
      path: '/iluminacion/reportes/$id/crud/create-resumen',
      getParentRoute: () => ProtectedRouteRoute,
    } as any,
  )
const ProtectedIluminacionReportesChar91idChar93CRUDCrudCreateGeneralRoute =
  ProtectedIluminacionReportesChar91idChar93CRUDCrudCreateGeneralRouteImport.update(
    {
      id: '/iluminacion/reportes/$id/_CRUD/crud/create-general',
      path: '/iluminacion/reportes/$id/crud/create-general',
      getParentRoute: () => ProtectedRouteRoute,
    } as any,
  )
const ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93PuntosRoute =
  ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93PuntosRouteImport.update(
    {
      id: '/iluminacion/reportes/$id/_CRUD/areas/$areaId/puntos',
      path: '/iluminacion/reportes/$id/areas/$areaId/puntos',
      getParentRoute: () => ProtectedRouteRoute,
    } as any,
  )
const ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93EditAreaRoute =
  ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93EditAreaRouteImport.update(
    {
      id: '/iluminacion/reportes/$id/_CRUD/areas/$areaId/edit-area',
      path: '/iluminacion/reportes/$id/areas/$areaId/edit-area',
      getParentRoute: () => ProtectedRouteRoute,
    } as any,
  )
const ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93CreateAreaRoute =
  ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93CreateAreaRouteImport.update(
    {
      id: '/iluminacion/reportes/$id/_CRUD/areas/$areaId/create-area',
      path: '/iluminacion/reportes/$id/areas/$areaId/create-area',
      getParentRoute: () => ProtectedRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/perfil': typeof ProtectedPerfilRouteRouteWithChildren
  '/suscripcion': typeof ProtectedSuscripcionRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/login/': typeof LoginIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/iluminacion/': typeof ProtectedIluminacionIndexRoute
  '/iluminacion/reportes/': typeof ProtectedIluminacionReportesIndexRoute
  '/perfil/empresas/': typeof ProtectedPerfilEmpresasIndexRoute
  '/perfil/instrumentos/': typeof ProtectedPerfilInstrumentosIndexRoute
  '/perfil/tecnicos/': typeof ProtectedPerfilTecnicosIndexRoute
  '/iluminacion/reportes/$id': typeof ProtectedIluminacionReportesChar91idChar93MenuRouteRouteWithChildren
  '/iluminacion/reportes/$id/areass': typeof ProtectedIluminacionReportesChar91idChar93MenuAreassRoute
  '/iluminacion/reportes/$id/general': typeof ProtectedIluminacionReportesChar91idChar93MenuGeneralRoute
  '/iluminacion/reportes/$id/resumen': typeof ProtectedIluminacionReportesChar91idChar93MenuResumenRoute
  '/iluminacion/reportes/pdf/$id/completa': typeof ProtectedIluminacionReportesPdfChar91idChar93CompletaRoute
  '/iluminacion/reportes/pdf/$id/reducida': typeof ProtectedIluminacionReportesPdfChar91idChar93ReducidaRoute
  '/iluminacion/reportes/$id/crud/create-general': typeof ProtectedIluminacionReportesChar91idChar93CRUDCrudCreateGeneralRoute
  '/iluminacion/reportes/$id/crud/create-resumen': typeof ProtectedIluminacionReportesChar91idChar93CRUDCrudCreateResumenRoute
  '/iluminacion/reportes/$id/crud/edit-general': typeof ProtectedIluminacionReportesChar91idChar93CRUDCrudEditGeneralRoute
  '/iluminacion/reportes/$id/crud/edit-resumen': typeof ProtectedIluminacionReportesChar91idChar93CRUDCrudEditResumenRoute
  '/iluminacion/reportes/$id/areas/': typeof ProtectedIluminacionReportesChar91idChar93CRUDAreasIndexRoute
  '/iluminacion/reportes/$id/areas/$areaId/create-area': typeof ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93CreateAreaRoute
  '/iluminacion/reportes/$id/areas/$areaId/edit-area': typeof ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93EditAreaRoute
  '/iluminacion/reportes/$id/areas/$areaId/puntos': typeof ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93PuntosRoute
}
export interface FileRoutesByTo {
  '/perfil': typeof ProtectedPerfilRouteRouteWithChildren
  '/suscripcion': typeof ProtectedSuscripcionRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/iluminacion': typeof ProtectedIluminacionIndexRoute
  '/iluminacion/reportes': typeof ProtectedIluminacionReportesIndexRoute
  '/perfil/empresas': typeof ProtectedPerfilEmpresasIndexRoute
  '/perfil/instrumentos': typeof ProtectedPerfilInstrumentosIndexRoute
  '/perfil/tecnicos': typeof ProtectedPerfilTecnicosIndexRoute
  '/iluminacion/reportes/$id': typeof ProtectedIluminacionReportesChar91idChar93MenuRouteRouteWithChildren
  '/iluminacion/reportes/$id/areass': typeof ProtectedIluminacionReportesChar91idChar93MenuAreassRoute
  '/iluminacion/reportes/$id/general': typeof ProtectedIluminacionReportesChar91idChar93MenuGeneralRoute
  '/iluminacion/reportes/$id/resumen': typeof ProtectedIluminacionReportesChar91idChar93MenuResumenRoute
  '/iluminacion/reportes/pdf/$id/completa': typeof ProtectedIluminacionReportesPdfChar91idChar93CompletaRoute
  '/iluminacion/reportes/pdf/$id/reducida': typeof ProtectedIluminacionReportesPdfChar91idChar93ReducidaRoute
  '/iluminacion/reportes/$id/crud/create-general': typeof ProtectedIluminacionReportesChar91idChar93CRUDCrudCreateGeneralRoute
  '/iluminacion/reportes/$id/crud/create-resumen': typeof ProtectedIluminacionReportesChar91idChar93CRUDCrudCreateResumenRoute
  '/iluminacion/reportes/$id/crud/edit-general': typeof ProtectedIluminacionReportesChar91idChar93CRUDCrudEditGeneralRoute
  '/iluminacion/reportes/$id/crud/edit-resumen': typeof ProtectedIluminacionReportesChar91idChar93CRUDCrudEditResumenRoute
  '/iluminacion/reportes/$id/areas': typeof ProtectedIluminacionReportesChar91idChar93CRUDAreasIndexRoute
  '/iluminacion/reportes/$id/areas/$areaId/create-area': typeof ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93CreateAreaRoute
  '/iluminacion/reportes/$id/areas/$areaId/edit-area': typeof ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93EditAreaRoute
  '/iluminacion/reportes/$id/areas/$areaId/puntos': typeof ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93PuntosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_protected/perfil': typeof ProtectedPerfilRouteRouteWithChildren
  '/_protected/suscripcion': typeof ProtectedSuscripcionRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/iluminacion/': typeof ProtectedIluminacionIndexRoute
  '/_protected/iluminacion/reportes/': typeof ProtectedIluminacionReportesIndexRoute
  '/_protected/perfil/empresas/': typeof ProtectedPerfilEmpresasIndexRoute
  '/_protected/perfil/instrumentos/': typeof ProtectedPerfilInstrumentosIndexRoute
  '/_protected/perfil/tecnicos/': typeof ProtectedPerfilTecnicosIndexRoute
  '/_protected/iluminacion/reportes/$id/_menu': typeof ProtectedIluminacionReportesChar91idChar93MenuRouteRouteWithChildren
  '/_protected/iluminacion/reportes/$id/_menu/areass': typeof ProtectedIluminacionReportesChar91idChar93MenuAreassRoute
  '/_protected/iluminacion/reportes/$id/_menu/general': typeof ProtectedIluminacionReportesChar91idChar93MenuGeneralRoute
  '/_protected/iluminacion/reportes/$id/_menu/resumen': typeof ProtectedIluminacionReportesChar91idChar93MenuResumenRoute
  '/_protected/iluminacion/reportes/pdf/$id/completa': typeof ProtectedIluminacionReportesPdfChar91idChar93CompletaRoute
  '/_protected/iluminacion/reportes/pdf/$id/reducida': typeof ProtectedIluminacionReportesPdfChar91idChar93ReducidaRoute
  '/_protected/iluminacion/reportes/$id/_CRUD/crud/create-general': typeof ProtectedIluminacionReportesChar91idChar93CRUDCrudCreateGeneralRoute
  '/_protected/iluminacion/reportes/$id/_CRUD/crud/create-resumen': typeof ProtectedIluminacionReportesChar91idChar93CRUDCrudCreateResumenRoute
  '/_protected/iluminacion/reportes/$id/_CRUD/crud/edit-general': typeof ProtectedIluminacionReportesChar91idChar93CRUDCrudEditGeneralRoute
  '/_protected/iluminacion/reportes/$id/_CRUD/crud/edit-resumen': typeof ProtectedIluminacionReportesChar91idChar93CRUDCrudEditResumenRoute
  '/_protected/iluminacion/reportes/$id/_CRUD/areas/': typeof ProtectedIluminacionReportesChar91idChar93CRUDAreasIndexRoute
  '/_protected/iluminacion/reportes/$id/_CRUD/areas/$areaId/create-area': typeof ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93CreateAreaRoute
  '/_protected/iluminacion/reportes/$id/_CRUD/areas/$areaId/edit-area': typeof ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93EditAreaRoute
  '/_protected/iluminacion/reportes/$id/_CRUD/areas/$areaId/puntos': typeof ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93PuntosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/perfil'
    | '/suscripcion'
    | '/api/uploadthing'
    | '/login/'
    | '/api/auth/$'
    | '/iluminacion/'
    | '/iluminacion/reportes/'
    | '/perfil/empresas/'
    | '/perfil/instrumentos/'
    | '/perfil/tecnicos/'
    | '/iluminacion/reportes/$id'
    | '/iluminacion/reportes/$id/areass'
    | '/iluminacion/reportes/$id/general'
    | '/iluminacion/reportes/$id/resumen'
    | '/iluminacion/reportes/pdf/$id/completa'
    | '/iluminacion/reportes/pdf/$id/reducida'
    | '/iluminacion/reportes/$id/crud/create-general'
    | '/iluminacion/reportes/$id/crud/create-resumen'
    | '/iluminacion/reportes/$id/crud/edit-general'
    | '/iluminacion/reportes/$id/crud/edit-resumen'
    | '/iluminacion/reportes/$id/areas/'
    | '/iluminacion/reportes/$id/areas/$areaId/create-area'
    | '/iluminacion/reportes/$id/areas/$areaId/edit-area'
    | '/iluminacion/reportes/$id/areas/$areaId/puntos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/perfil'
    | '/suscripcion'
    | '/api/uploadthing'
    | '/'
    | '/login'
    | '/api/auth/$'
    | '/iluminacion'
    | '/iluminacion/reportes'
    | '/perfil/empresas'
    | '/perfil/instrumentos'
    | '/perfil/tecnicos'
    | '/iluminacion/reportes/$id'
    | '/iluminacion/reportes/$id/areass'
    | '/iluminacion/reportes/$id/general'
    | '/iluminacion/reportes/$id/resumen'
    | '/iluminacion/reportes/pdf/$id/completa'
    | '/iluminacion/reportes/pdf/$id/reducida'
    | '/iluminacion/reportes/$id/crud/create-general'
    | '/iluminacion/reportes/$id/crud/create-resumen'
    | '/iluminacion/reportes/$id/crud/edit-general'
    | '/iluminacion/reportes/$id/crud/edit-resumen'
    | '/iluminacion/reportes/$id/areas'
    | '/iluminacion/reportes/$id/areas/$areaId/create-area'
    | '/iluminacion/reportes/$id/areas/$areaId/edit-area'
    | '/iluminacion/reportes/$id/areas/$areaId/puntos'
  id:
    | '__root__'
    | '/_protected'
    | '/_protected/perfil'
    | '/_protected/suscripcion'
    | '/api/uploadthing'
    | '/_protected/'
    | '/login/'
    | '/api/auth/$'
    | '/_protected/iluminacion/'
    | '/_protected/iluminacion/reportes/'
    | '/_protected/perfil/empresas/'
    | '/_protected/perfil/instrumentos/'
    | '/_protected/perfil/tecnicos/'
    | '/_protected/iluminacion/reportes/$id/_menu'
    | '/_protected/iluminacion/reportes/$id/_menu/areass'
    | '/_protected/iluminacion/reportes/$id/_menu/general'
    | '/_protected/iluminacion/reportes/$id/_menu/resumen'
    | '/_protected/iluminacion/reportes/pdf/$id/completa'
    | '/_protected/iluminacion/reportes/pdf/$id/reducida'
    | '/_protected/iluminacion/reportes/$id/_CRUD/crud/create-general'
    | '/_protected/iluminacion/reportes/$id/_CRUD/crud/create-resumen'
    | '/_protected/iluminacion/reportes/$id/_CRUD/crud/edit-general'
    | '/_protected/iluminacion/reportes/$id/_CRUD/crud/edit-resumen'
    | '/_protected/iluminacion/reportes/$id/_CRUD/areas/'
    | '/_protected/iluminacion/reportes/$id/_CRUD/areas/$areaId/create-area'
    | '/_protected/iluminacion/reportes/$id/_CRUD/areas/$areaId/edit-area'
    | '/_protected/iluminacion/reportes/$id/_CRUD/areas/$areaId/puntos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/suscripcion': {
      id: '/_protected/suscripcion'
      path: '/suscripcion'
      fullPath: '/suscripcion'
      preLoaderRoute: typeof ProtectedSuscripcionRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/perfil': {
      id: '/_protected/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof ProtectedPerfilRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/iluminacion/': {
      id: '/_protected/iluminacion/'
      path: '/iluminacion'
      fullPath: '/iluminacion/'
      preLoaderRoute: typeof ProtectedIluminacionIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/perfil/tecnicos/': {
      id: '/_protected/perfil/tecnicos/'
      path: '/tecnicos'
      fullPath: '/perfil/tecnicos/'
      preLoaderRoute: typeof ProtectedPerfilTecnicosIndexRouteImport
      parentRoute: typeof ProtectedPerfilRouteRoute
    }
    '/_protected/perfil/instrumentos/': {
      id: '/_protected/perfil/instrumentos/'
      path: '/instrumentos'
      fullPath: '/perfil/instrumentos/'
      preLoaderRoute: typeof ProtectedPerfilInstrumentosIndexRouteImport
      parentRoute: typeof ProtectedPerfilRouteRoute
    }
    '/_protected/perfil/empresas/': {
      id: '/_protected/perfil/empresas/'
      path: '/empresas'
      fullPath: '/perfil/empresas/'
      preLoaderRoute: typeof ProtectedPerfilEmpresasIndexRouteImport
      parentRoute: typeof ProtectedPerfilRouteRoute
    }
    '/_protected/iluminacion/reportes/': {
      id: '/_protected/iluminacion/reportes/'
      path: '/iluminacion/reportes'
      fullPath: '/iluminacion/reportes/'
      preLoaderRoute: typeof ProtectedIluminacionReportesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/iluminacion/reportes/$id/_menu': {
      id: '/_protected/iluminacion/reportes/$id/_menu'
      path: '/iluminacion/reportes/$id'
      fullPath: '/iluminacion/reportes/$id'
      preLoaderRoute: typeof ProtectedIluminacionReportesChar91idChar93MenuRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/iluminacion/reportes/pdf/$id/reducida': {
      id: '/_protected/iluminacion/reportes/pdf/$id/reducida'
      path: '/iluminacion/reportes/pdf/$id/reducida'
      fullPath: '/iluminacion/reportes/pdf/$id/reducida'
      preLoaderRoute: typeof ProtectedIluminacionReportesPdfChar91idChar93ReducidaRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/iluminacion/reportes/pdf/$id/completa': {
      id: '/_protected/iluminacion/reportes/pdf/$id/completa'
      path: '/iluminacion/reportes/pdf/$id/completa'
      fullPath: '/iluminacion/reportes/pdf/$id/completa'
      preLoaderRoute: typeof ProtectedIluminacionReportesPdfChar91idChar93CompletaRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/iluminacion/reportes/$id/_menu/resumen': {
      id: '/_protected/iluminacion/reportes/$id/_menu/resumen'
      path: '/resumen'
      fullPath: '/iluminacion/reportes/$id/resumen'
      preLoaderRoute: typeof ProtectedIluminacionReportesChar91idChar93MenuResumenRouteImport
      parentRoute: typeof ProtectedIluminacionReportesChar91idChar93MenuRouteRoute
    }
    '/_protected/iluminacion/reportes/$id/_menu/general': {
      id: '/_protected/iluminacion/reportes/$id/_menu/general'
      path: '/general'
      fullPath: '/iluminacion/reportes/$id/general'
      preLoaderRoute: typeof ProtectedIluminacionReportesChar91idChar93MenuGeneralRouteImport
      parentRoute: typeof ProtectedIluminacionReportesChar91idChar93MenuRouteRoute
    }
    '/_protected/iluminacion/reportes/$id/_menu/areass': {
      id: '/_protected/iluminacion/reportes/$id/_menu/areass'
      path: '/areass'
      fullPath: '/iluminacion/reportes/$id/areass'
      preLoaderRoute: typeof ProtectedIluminacionReportesChar91idChar93MenuAreassRouteImport
      parentRoute: typeof ProtectedIluminacionReportesChar91idChar93MenuRouteRoute
    }
    '/_protected/iluminacion/reportes/$id/_CRUD/areas/': {
      id: '/_protected/iluminacion/reportes/$id/_CRUD/areas/'
      path: '/iluminacion/reportes/$id/areas'
      fullPath: '/iluminacion/reportes/$id/areas/'
      preLoaderRoute: typeof ProtectedIluminacionReportesChar91idChar93CRUDAreasIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/iluminacion/reportes/$id/_CRUD/crud/edit-resumen': {
      id: '/_protected/iluminacion/reportes/$id/_CRUD/crud/edit-resumen'
      path: '/iluminacion/reportes/$id/crud/edit-resumen'
      fullPath: '/iluminacion/reportes/$id/crud/edit-resumen'
      preLoaderRoute: typeof ProtectedIluminacionReportesChar91idChar93CRUDCrudEditResumenRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/iluminacion/reportes/$id/_CRUD/crud/edit-general': {
      id: '/_protected/iluminacion/reportes/$id/_CRUD/crud/edit-general'
      path: '/iluminacion/reportes/$id/crud/edit-general'
      fullPath: '/iluminacion/reportes/$id/crud/edit-general'
      preLoaderRoute: typeof ProtectedIluminacionReportesChar91idChar93CRUDCrudEditGeneralRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/iluminacion/reportes/$id/_CRUD/crud/create-resumen': {
      id: '/_protected/iluminacion/reportes/$id/_CRUD/crud/create-resumen'
      path: '/iluminacion/reportes/$id/crud/create-resumen'
      fullPath: '/iluminacion/reportes/$id/crud/create-resumen'
      preLoaderRoute: typeof ProtectedIluminacionReportesChar91idChar93CRUDCrudCreateResumenRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/iluminacion/reportes/$id/_CRUD/crud/create-general': {
      id: '/_protected/iluminacion/reportes/$id/_CRUD/crud/create-general'
      path: '/iluminacion/reportes/$id/crud/create-general'
      fullPath: '/iluminacion/reportes/$id/crud/create-general'
      preLoaderRoute: typeof ProtectedIluminacionReportesChar91idChar93CRUDCrudCreateGeneralRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/iluminacion/reportes/$id/_CRUD/areas/$areaId/puntos': {
      id: '/_protected/iluminacion/reportes/$id/_CRUD/areas/$areaId/puntos'
      path: '/iluminacion/reportes/$id/areas/$areaId/puntos'
      fullPath: '/iluminacion/reportes/$id/areas/$areaId/puntos'
      preLoaderRoute: typeof ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93PuntosRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/iluminacion/reportes/$id/_CRUD/areas/$areaId/edit-area': {
      id: '/_protected/iluminacion/reportes/$id/_CRUD/areas/$areaId/edit-area'
      path: '/iluminacion/reportes/$id/areas/$areaId/edit-area'
      fullPath: '/iluminacion/reportes/$id/areas/$areaId/edit-area'
      preLoaderRoute: typeof ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93EditAreaRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/iluminacion/reportes/$id/_CRUD/areas/$areaId/create-area': {
      id: '/_protected/iluminacion/reportes/$id/_CRUD/areas/$areaId/create-area'
      path: '/iluminacion/reportes/$id/areas/$areaId/create-area'
      fullPath: '/iluminacion/reportes/$id/areas/$areaId/create-area'
      preLoaderRoute: typeof ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93CreateAreaRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedPerfilRouteRouteChildren {
  ProtectedPerfilEmpresasIndexRoute: typeof ProtectedPerfilEmpresasIndexRoute
  ProtectedPerfilInstrumentosIndexRoute: typeof ProtectedPerfilInstrumentosIndexRoute
  ProtectedPerfilTecnicosIndexRoute: typeof ProtectedPerfilTecnicosIndexRoute
}

const ProtectedPerfilRouteRouteChildren: ProtectedPerfilRouteRouteChildren = {
  ProtectedPerfilEmpresasIndexRoute: ProtectedPerfilEmpresasIndexRoute,
  ProtectedPerfilInstrumentosIndexRoute: ProtectedPerfilInstrumentosIndexRoute,
  ProtectedPerfilTecnicosIndexRoute: ProtectedPerfilTecnicosIndexRoute,
}

const ProtectedPerfilRouteRouteWithChildren =
  ProtectedPerfilRouteRoute._addFileChildren(ProtectedPerfilRouteRouteChildren)

interface ProtectedIluminacionReportesChar91idChar93MenuRouteRouteChildren {
  ProtectedIluminacionReportesChar91idChar93MenuAreassRoute: typeof ProtectedIluminacionReportesChar91idChar93MenuAreassRoute
  ProtectedIluminacionReportesChar91idChar93MenuGeneralRoute: typeof ProtectedIluminacionReportesChar91idChar93MenuGeneralRoute
  ProtectedIluminacionReportesChar91idChar93MenuResumenRoute: typeof ProtectedIluminacionReportesChar91idChar93MenuResumenRoute
}

const ProtectedIluminacionReportesChar91idChar93MenuRouteRouteChildren: ProtectedIluminacionReportesChar91idChar93MenuRouteRouteChildren =
  {
    ProtectedIluminacionReportesChar91idChar93MenuAreassRoute:
      ProtectedIluminacionReportesChar91idChar93MenuAreassRoute,
    ProtectedIluminacionReportesChar91idChar93MenuGeneralRoute:
      ProtectedIluminacionReportesChar91idChar93MenuGeneralRoute,
    ProtectedIluminacionReportesChar91idChar93MenuResumenRoute:
      ProtectedIluminacionReportesChar91idChar93MenuResumenRoute,
  }

const ProtectedIluminacionReportesChar91idChar93MenuRouteRouteWithChildren =
  ProtectedIluminacionReportesChar91idChar93MenuRouteRoute._addFileChildren(
    ProtectedIluminacionReportesChar91idChar93MenuRouteRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedPerfilRouteRoute: typeof ProtectedPerfilRouteRouteWithChildren
  ProtectedSuscripcionRoute: typeof ProtectedSuscripcionRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedIluminacionIndexRoute: typeof ProtectedIluminacionIndexRoute
  ProtectedIluminacionReportesIndexRoute: typeof ProtectedIluminacionReportesIndexRoute
  ProtectedIluminacionReportesChar91idChar93MenuRouteRoute: typeof ProtectedIluminacionReportesChar91idChar93MenuRouteRouteWithChildren
  ProtectedIluminacionReportesPdfChar91idChar93CompletaRoute: typeof ProtectedIluminacionReportesPdfChar91idChar93CompletaRoute
  ProtectedIluminacionReportesPdfChar91idChar93ReducidaRoute: typeof ProtectedIluminacionReportesPdfChar91idChar93ReducidaRoute
  ProtectedIluminacionReportesChar91idChar93CRUDCrudCreateGeneralRoute: typeof ProtectedIluminacionReportesChar91idChar93CRUDCrudCreateGeneralRoute
  ProtectedIluminacionReportesChar91idChar93CRUDCrudCreateResumenRoute: typeof ProtectedIluminacionReportesChar91idChar93CRUDCrudCreateResumenRoute
  ProtectedIluminacionReportesChar91idChar93CRUDCrudEditGeneralRoute: typeof ProtectedIluminacionReportesChar91idChar93CRUDCrudEditGeneralRoute
  ProtectedIluminacionReportesChar91idChar93CRUDCrudEditResumenRoute: typeof ProtectedIluminacionReportesChar91idChar93CRUDCrudEditResumenRoute
  ProtectedIluminacionReportesChar91idChar93CRUDAreasIndexRoute: typeof ProtectedIluminacionReportesChar91idChar93CRUDAreasIndexRoute
  ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93CreateAreaRoute: typeof ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93CreateAreaRoute
  ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93EditAreaRoute: typeof ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93EditAreaRoute
  ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93PuntosRoute: typeof ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93PuntosRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedPerfilRouteRoute: ProtectedPerfilRouteRouteWithChildren,
  ProtectedSuscripcionRoute: ProtectedSuscripcionRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedIluminacionIndexRoute: ProtectedIluminacionIndexRoute,
  ProtectedIluminacionReportesIndexRoute:
    ProtectedIluminacionReportesIndexRoute,
  ProtectedIluminacionReportesChar91idChar93MenuRouteRoute:
    ProtectedIluminacionReportesChar91idChar93MenuRouteRouteWithChildren,
  ProtectedIluminacionReportesPdfChar91idChar93CompletaRoute:
    ProtectedIluminacionReportesPdfChar91idChar93CompletaRoute,
  ProtectedIluminacionReportesPdfChar91idChar93ReducidaRoute:
    ProtectedIluminacionReportesPdfChar91idChar93ReducidaRoute,
  ProtectedIluminacionReportesChar91idChar93CRUDCrudCreateGeneralRoute:
    ProtectedIluminacionReportesChar91idChar93CRUDCrudCreateGeneralRoute,
  ProtectedIluminacionReportesChar91idChar93CRUDCrudCreateResumenRoute:
    ProtectedIluminacionReportesChar91idChar93CRUDCrudCreateResumenRoute,
  ProtectedIluminacionReportesChar91idChar93CRUDCrudEditGeneralRoute:
    ProtectedIluminacionReportesChar91idChar93CRUDCrudEditGeneralRoute,
  ProtectedIluminacionReportesChar91idChar93CRUDCrudEditResumenRoute:
    ProtectedIluminacionReportesChar91idChar93CRUDCrudEditResumenRoute,
  ProtectedIluminacionReportesChar91idChar93CRUDAreasIndexRoute:
    ProtectedIluminacionReportesChar91idChar93CRUDAreasIndexRoute,
  ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93CreateAreaRoute:
    ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93CreateAreaRoute,
  ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93EditAreaRoute:
    ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93EditAreaRoute,
  ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93PuntosRoute:
    ProtectedIluminacionReportesChar91idChar93CRUDAreasChar91areaIdChar93PuntosRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  ApiUploadthingRoute: ApiUploadthingRoute,
  LoginIndexRoute: LoginIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
