/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoadingRouteImport } from './routes/loading'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedSuscripcionRouteImport } from './routes/_protected/suscripcion'
import { Route as ProtectedIluminacionIndexRouteImport } from './routes/_protected/iluminacion/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const LoadingRoute = LoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSuscripcionRoute = ProtectedSuscripcionRouteImport.update({
  id: '/suscripcion',
  path: '/suscripcion',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedIluminacionIndexRoute =
  ProtectedIluminacionIndexRouteImport.update({
    id: '/iluminacion/',
    path: '/iluminacion/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/loading': typeof LoadingRoute
  '/suscripcion': typeof ProtectedSuscripcionRoute
  '/login/': typeof LoginIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/iluminacion/': typeof ProtectedIluminacionIndexRoute
}
export interface FileRoutesByTo {
  '/loading': typeof LoadingRoute
  '/suscripcion': typeof ProtectedSuscripcionRoute
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/iluminacion': typeof ProtectedIluminacionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/loading': typeof LoadingRoute
  '/_protected/suscripcion': typeof ProtectedSuscripcionRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/iluminacion/': typeof ProtectedIluminacionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/loading'
    | '/suscripcion'
    | '/login/'
    | '/api/auth/$'
    | '/iluminacion/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/loading'
    | '/suscripcion'
    | '/'
    | '/login'
    | '/api/auth/$'
    | '/iluminacion'
  id:
    | '__root__'
    | '/_protected'
    | '/loading'
    | '/_protected/suscripcion'
    | '/_protected/'
    | '/login/'
    | '/api/auth/$'
    | '/_protected/iluminacion/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  LoadingRoute: typeof LoadingRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/loading': {
      id: '/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof LoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/suscripcion': {
      id: '/_protected/suscripcion'
      path: '/suscripcion'
      fullPath: '/suscripcion'
      preLoaderRoute: typeof ProtectedSuscripcionRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/iluminacion/': {
      id: '/_protected/iluminacion/'
      path: '/iluminacion'
      fullPath: '/iluminacion/'
      preLoaderRoute: typeof ProtectedIluminacionIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedSuscripcionRoute: typeof ProtectedSuscripcionRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedIluminacionIndexRoute: typeof ProtectedIluminacionIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedSuscripcionRoute: ProtectedSuscripcionRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedIluminacionIndexRoute: ProtectedIluminacionIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  LoadingRoute: LoadingRoute,
  LoginIndexRoute: LoginIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
