/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as ProtectedSuscripcionRouteImport } from './routes/_protected/suscripcion'
import { Route as ProtectedPerfilRouteRouteImport } from './routes/_protected/perfil/route'
import { Route as ProtectedIluminacionIndexRouteImport } from './routes/_protected/iluminacion/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedPerfilTecnicosIndexRouteImport } from './routes/_protected/perfil/tecnicos/index'
import { Route as ProtectedPerfilInstrumentosIndexRouteImport } from './routes/_protected/perfil/instrumentos/index'
import { Route as ProtectedPerfilEmpresasIndexRouteImport } from './routes/_protected/perfil/empresas/index'
import { Route as ProtectedIluminacionReportesIndexRouteImport } from './routes/_protected/iluminacion/reportes/index'
import { Route as ProtectedIluminacionNuevoInformeIndexRouteImport } from './routes/_protected/iluminacion/nuevo-informe/index'
import { Route as ProtectedIluminacionReportesChar91idChar93RouteRouteImport } from './routes/_protected/iluminacion/reportes/[$id]/route'
import { Route as ProtectedIluminacionNuevoInformeOpinionIndexRouteImport } from './routes/_protected/iluminacion/nuevo-informe/opinion/index'
import { Route as ProtectedIluminacionNuevoInformeAreasIndexRouteImport } from './routes/_protected/iluminacion/nuevo-informe/areas/index'
import { Route as ProtectedIluminacionReportesChar91idChar93ResumenRouteImport } from './routes/_protected/iluminacion/reportes/[$id]/resumen'
import { Route as ProtectedIluminacionReportesChar91idChar93GeneralRouteImport } from './routes/_protected/iluminacion/reportes/[$id]/general'
import { Route as ProtectedIluminacionReportesChar91idChar93AreasRouteImport } from './routes/_protected/iluminacion/reportes/[$id]/areas'
import { Route as ProtectedIluminacionReportesPdfChar91idChar93IndexRouteImport } from './routes/_protected/iluminacion/reportes/pdf/[$id]/index'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSuscripcionRoute = ProtectedSuscripcionRouteImport.update({
  id: '/suscripcion',
  path: '/suscripcion',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedPerfilRouteRoute = ProtectedPerfilRouteRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedIluminacionIndexRoute =
  ProtectedIluminacionIndexRouteImport.update({
    id: '/iluminacion/',
    path: '/iluminacion/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPerfilTecnicosIndexRoute =
  ProtectedPerfilTecnicosIndexRouteImport.update({
    id: '/tecnicos/',
    path: '/tecnicos/',
    getParentRoute: () => ProtectedPerfilRouteRoute,
  } as any)
const ProtectedPerfilInstrumentosIndexRoute =
  ProtectedPerfilInstrumentosIndexRouteImport.update({
    id: '/instrumentos/',
    path: '/instrumentos/',
    getParentRoute: () => ProtectedPerfilRouteRoute,
  } as any)
const ProtectedPerfilEmpresasIndexRoute =
  ProtectedPerfilEmpresasIndexRouteImport.update({
    id: '/empresas/',
    path: '/empresas/',
    getParentRoute: () => ProtectedPerfilRouteRoute,
  } as any)
const ProtectedIluminacionReportesIndexRoute =
  ProtectedIluminacionReportesIndexRouteImport.update({
    id: '/iluminacion/reportes/',
    path: '/iluminacion/reportes/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedIluminacionNuevoInformeIndexRoute =
  ProtectedIluminacionNuevoInformeIndexRouteImport.update({
    id: '/iluminacion/nuevo-informe/',
    path: '/iluminacion/nuevo-informe/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedIluminacionReportesChar91idChar93RouteRoute =
  ProtectedIluminacionReportesChar91idChar93RouteRouteImport.update({
    id: '/iluminacion/reportes/$id',
    path: '/iluminacion/reportes/$id',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedIluminacionNuevoInformeOpinionIndexRoute =
  ProtectedIluminacionNuevoInformeOpinionIndexRouteImport.update({
    id: '/iluminacion/nuevo-informe/opinion/',
    path: '/iluminacion/nuevo-informe/opinion/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedIluminacionNuevoInformeAreasIndexRoute =
  ProtectedIluminacionNuevoInformeAreasIndexRouteImport.update({
    id: '/iluminacion/nuevo-informe/areas/',
    path: '/iluminacion/nuevo-informe/areas/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedIluminacionReportesChar91idChar93ResumenRoute =
  ProtectedIluminacionReportesChar91idChar93ResumenRouteImport.update({
    id: '/resumen',
    path: '/resumen',
    getParentRoute: () => ProtectedIluminacionReportesChar91idChar93RouteRoute,
  } as any)
const ProtectedIluminacionReportesChar91idChar93GeneralRoute =
  ProtectedIluminacionReportesChar91idChar93GeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => ProtectedIluminacionReportesChar91idChar93RouteRoute,
  } as any)
const ProtectedIluminacionReportesChar91idChar93AreasRoute =
  ProtectedIluminacionReportesChar91idChar93AreasRouteImport.update({
    id: '/areas',
    path: '/areas',
    getParentRoute: () => ProtectedIluminacionReportesChar91idChar93RouteRoute,
  } as any)
const ProtectedIluminacionReportesPdfChar91idChar93IndexRoute =
  ProtectedIluminacionReportesPdfChar91idChar93IndexRouteImport.update({
    id: '/iluminacion/reportes/pdf/$id/',
    path: '/iluminacion/reportes/pdf/$id/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/perfil': typeof ProtectedPerfilRouteRouteWithChildren
  '/suscripcion': typeof ProtectedSuscripcionRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/login/': typeof LoginIndexRoute
  '/test/': typeof TestIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/iluminacion/': typeof ProtectedIluminacionIndexRoute
  '/iluminacion/reportes/$id': typeof ProtectedIluminacionReportesChar91idChar93RouteRouteWithChildren
  '/iluminacion/nuevo-informe/': typeof ProtectedIluminacionNuevoInformeIndexRoute
  '/iluminacion/reportes/': typeof ProtectedIluminacionReportesIndexRoute
  '/perfil/empresas/': typeof ProtectedPerfilEmpresasIndexRoute
  '/perfil/instrumentos/': typeof ProtectedPerfilInstrumentosIndexRoute
  '/perfil/tecnicos/': typeof ProtectedPerfilTecnicosIndexRoute
  '/iluminacion/reportes/$id/areas': typeof ProtectedIluminacionReportesChar91idChar93AreasRoute
  '/iluminacion/reportes/$id/general': typeof ProtectedIluminacionReportesChar91idChar93GeneralRoute
  '/iluminacion/reportes/$id/resumen': typeof ProtectedIluminacionReportesChar91idChar93ResumenRoute
  '/iluminacion/nuevo-informe/areas/': typeof ProtectedIluminacionNuevoInformeAreasIndexRoute
  '/iluminacion/nuevo-informe/opinion/': typeof ProtectedIluminacionNuevoInformeOpinionIndexRoute
  '/iluminacion/reportes/pdf/$id/': typeof ProtectedIluminacionReportesPdfChar91idChar93IndexRoute
}
export interface FileRoutesByTo {
  '/perfil': typeof ProtectedPerfilRouteRouteWithChildren
  '/suscripcion': typeof ProtectedSuscripcionRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginIndexRoute
  '/test': typeof TestIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/iluminacion': typeof ProtectedIluminacionIndexRoute
  '/iluminacion/reportes/$id': typeof ProtectedIluminacionReportesChar91idChar93RouteRouteWithChildren
  '/iluminacion/nuevo-informe': typeof ProtectedIluminacionNuevoInformeIndexRoute
  '/iluminacion/reportes': typeof ProtectedIluminacionReportesIndexRoute
  '/perfil/empresas': typeof ProtectedPerfilEmpresasIndexRoute
  '/perfil/instrumentos': typeof ProtectedPerfilInstrumentosIndexRoute
  '/perfil/tecnicos': typeof ProtectedPerfilTecnicosIndexRoute
  '/iluminacion/reportes/$id/areas': typeof ProtectedIluminacionReportesChar91idChar93AreasRoute
  '/iluminacion/reportes/$id/general': typeof ProtectedIluminacionReportesChar91idChar93GeneralRoute
  '/iluminacion/reportes/$id/resumen': typeof ProtectedIluminacionReportesChar91idChar93ResumenRoute
  '/iluminacion/nuevo-informe/areas': typeof ProtectedIluminacionNuevoInformeAreasIndexRoute
  '/iluminacion/nuevo-informe/opinion': typeof ProtectedIluminacionNuevoInformeOpinionIndexRoute
  '/iluminacion/reportes/pdf/$id': typeof ProtectedIluminacionReportesPdfChar91idChar93IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_protected/perfil': typeof ProtectedPerfilRouteRouteWithChildren
  '/_protected/suscripcion': typeof ProtectedSuscripcionRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/login/': typeof LoginIndexRoute
  '/test/': typeof TestIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/iluminacion/': typeof ProtectedIluminacionIndexRoute
  '/_protected/iluminacion/reportes/$id': typeof ProtectedIluminacionReportesChar91idChar93RouteRouteWithChildren
  '/_protected/iluminacion/nuevo-informe/': typeof ProtectedIluminacionNuevoInformeIndexRoute
  '/_protected/iluminacion/reportes/': typeof ProtectedIluminacionReportesIndexRoute
  '/_protected/perfil/empresas/': typeof ProtectedPerfilEmpresasIndexRoute
  '/_protected/perfil/instrumentos/': typeof ProtectedPerfilInstrumentosIndexRoute
  '/_protected/perfil/tecnicos/': typeof ProtectedPerfilTecnicosIndexRoute
  '/_protected/iluminacion/reportes/$id/areas': typeof ProtectedIluminacionReportesChar91idChar93AreasRoute
  '/_protected/iluminacion/reportes/$id/general': typeof ProtectedIluminacionReportesChar91idChar93GeneralRoute
  '/_protected/iluminacion/reportes/$id/resumen': typeof ProtectedIluminacionReportesChar91idChar93ResumenRoute
  '/_protected/iluminacion/nuevo-informe/areas/': typeof ProtectedIluminacionNuevoInformeAreasIndexRoute
  '/_protected/iluminacion/nuevo-informe/opinion/': typeof ProtectedIluminacionNuevoInformeOpinionIndexRoute
  '/_protected/iluminacion/reportes/pdf/$id/': typeof ProtectedIluminacionReportesPdfChar91idChar93IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/perfil'
    | '/suscripcion'
    | '/api/uploadthing'
    | '/login/'
    | '/test/'
    | '/api/auth/$'
    | '/iluminacion/'
    | '/iluminacion/reportes/$id'
    | '/iluminacion/nuevo-informe/'
    | '/iluminacion/reportes/'
    | '/perfil/empresas/'
    | '/perfil/instrumentos/'
    | '/perfil/tecnicos/'
    | '/iluminacion/reportes/$id/areas'
    | '/iluminacion/reportes/$id/general'
    | '/iluminacion/reportes/$id/resumen'
    | '/iluminacion/nuevo-informe/areas/'
    | '/iluminacion/nuevo-informe/opinion/'
    | '/iluminacion/reportes/pdf/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/perfil'
    | '/suscripcion'
    | '/api/uploadthing'
    | '/'
    | '/login'
    | '/test'
    | '/api/auth/$'
    | '/iluminacion'
    | '/iluminacion/reportes/$id'
    | '/iluminacion/nuevo-informe'
    | '/iluminacion/reportes'
    | '/perfil/empresas'
    | '/perfil/instrumentos'
    | '/perfil/tecnicos'
    | '/iluminacion/reportes/$id/areas'
    | '/iluminacion/reportes/$id/general'
    | '/iluminacion/reportes/$id/resumen'
    | '/iluminacion/nuevo-informe/areas'
    | '/iluminacion/nuevo-informe/opinion'
    | '/iluminacion/reportes/pdf/$id'
  id:
    | '__root__'
    | '/_protected'
    | '/_protected/perfil'
    | '/_protected/suscripcion'
    | '/api/uploadthing'
    | '/_protected/'
    | '/login/'
    | '/test/'
    | '/api/auth/$'
    | '/_protected/iluminacion/'
    | '/_protected/iluminacion/reportes/$id'
    | '/_protected/iluminacion/nuevo-informe/'
    | '/_protected/iluminacion/reportes/'
    | '/_protected/perfil/empresas/'
    | '/_protected/perfil/instrumentos/'
    | '/_protected/perfil/tecnicos/'
    | '/_protected/iluminacion/reportes/$id/areas'
    | '/_protected/iluminacion/reportes/$id/general'
    | '/_protected/iluminacion/reportes/$id/resumen'
    | '/_protected/iluminacion/nuevo-informe/areas/'
    | '/_protected/iluminacion/nuevo-informe/opinion/'
    | '/_protected/iluminacion/reportes/pdf/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  LoginIndexRoute: typeof LoginIndexRoute
  TestIndexRoute: typeof TestIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/suscripcion': {
      id: '/_protected/suscripcion'
      path: '/suscripcion'
      fullPath: '/suscripcion'
      preLoaderRoute: typeof ProtectedSuscripcionRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/perfil': {
      id: '/_protected/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof ProtectedPerfilRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/iluminacion/': {
      id: '/_protected/iluminacion/'
      path: '/iluminacion'
      fullPath: '/iluminacion/'
      preLoaderRoute: typeof ProtectedIluminacionIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/perfil/tecnicos/': {
      id: '/_protected/perfil/tecnicos/'
      path: '/tecnicos'
      fullPath: '/perfil/tecnicos/'
      preLoaderRoute: typeof ProtectedPerfilTecnicosIndexRouteImport
      parentRoute: typeof ProtectedPerfilRouteRoute
    }
    '/_protected/perfil/instrumentos/': {
      id: '/_protected/perfil/instrumentos/'
      path: '/instrumentos'
      fullPath: '/perfil/instrumentos/'
      preLoaderRoute: typeof ProtectedPerfilInstrumentosIndexRouteImport
      parentRoute: typeof ProtectedPerfilRouteRoute
    }
    '/_protected/perfil/empresas/': {
      id: '/_protected/perfil/empresas/'
      path: '/empresas'
      fullPath: '/perfil/empresas/'
      preLoaderRoute: typeof ProtectedPerfilEmpresasIndexRouteImport
      parentRoute: typeof ProtectedPerfilRouteRoute
    }
    '/_protected/iluminacion/reportes/': {
      id: '/_protected/iluminacion/reportes/'
      path: '/iluminacion/reportes'
      fullPath: '/iluminacion/reportes/'
      preLoaderRoute: typeof ProtectedIluminacionReportesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/iluminacion/nuevo-informe/': {
      id: '/_protected/iluminacion/nuevo-informe/'
      path: '/iluminacion/nuevo-informe'
      fullPath: '/iluminacion/nuevo-informe/'
      preLoaderRoute: typeof ProtectedIluminacionNuevoInformeIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/iluminacion/reportes/$id': {
      id: '/_protected/iluminacion/reportes/$id'
      path: '/iluminacion/reportes/$id'
      fullPath: '/iluminacion/reportes/$id'
      preLoaderRoute: typeof ProtectedIluminacionReportesChar91idChar93RouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/iluminacion/nuevo-informe/opinion/': {
      id: '/_protected/iluminacion/nuevo-informe/opinion/'
      path: '/iluminacion/nuevo-informe/opinion'
      fullPath: '/iluminacion/nuevo-informe/opinion/'
      preLoaderRoute: typeof ProtectedIluminacionNuevoInformeOpinionIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/iluminacion/nuevo-informe/areas/': {
      id: '/_protected/iluminacion/nuevo-informe/areas/'
      path: '/iluminacion/nuevo-informe/areas'
      fullPath: '/iluminacion/nuevo-informe/areas/'
      preLoaderRoute: typeof ProtectedIluminacionNuevoInformeAreasIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/iluminacion/reportes/$id/resumen': {
      id: '/_protected/iluminacion/reportes/$id/resumen'
      path: '/resumen'
      fullPath: '/iluminacion/reportes/$id/resumen'
      preLoaderRoute: typeof ProtectedIluminacionReportesChar91idChar93ResumenRouteImport
      parentRoute: typeof ProtectedIluminacionReportesChar91idChar93RouteRoute
    }
    '/_protected/iluminacion/reportes/$id/general': {
      id: '/_protected/iluminacion/reportes/$id/general'
      path: '/general'
      fullPath: '/iluminacion/reportes/$id/general'
      preLoaderRoute: typeof ProtectedIluminacionReportesChar91idChar93GeneralRouteImport
      parentRoute: typeof ProtectedIluminacionReportesChar91idChar93RouteRoute
    }
    '/_protected/iluminacion/reportes/$id/areas': {
      id: '/_protected/iluminacion/reportes/$id/areas'
      path: '/areas'
      fullPath: '/iluminacion/reportes/$id/areas'
      preLoaderRoute: typeof ProtectedIluminacionReportesChar91idChar93AreasRouteImport
      parentRoute: typeof ProtectedIluminacionReportesChar91idChar93RouteRoute
    }
    '/_protected/iluminacion/reportes/pdf/$id/': {
      id: '/_protected/iluminacion/reportes/pdf/$id/'
      path: '/iluminacion/reportes/pdf/$id'
      fullPath: '/iluminacion/reportes/pdf/$id/'
      preLoaderRoute: typeof ProtectedIluminacionReportesPdfChar91idChar93IndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedPerfilRouteRouteChildren {
  ProtectedPerfilEmpresasIndexRoute: typeof ProtectedPerfilEmpresasIndexRoute
  ProtectedPerfilInstrumentosIndexRoute: typeof ProtectedPerfilInstrumentosIndexRoute
  ProtectedPerfilTecnicosIndexRoute: typeof ProtectedPerfilTecnicosIndexRoute
}

const ProtectedPerfilRouteRouteChildren: ProtectedPerfilRouteRouteChildren = {
  ProtectedPerfilEmpresasIndexRoute: ProtectedPerfilEmpresasIndexRoute,
  ProtectedPerfilInstrumentosIndexRoute: ProtectedPerfilInstrumentosIndexRoute,
  ProtectedPerfilTecnicosIndexRoute: ProtectedPerfilTecnicosIndexRoute,
}

const ProtectedPerfilRouteRouteWithChildren =
  ProtectedPerfilRouteRoute._addFileChildren(ProtectedPerfilRouteRouteChildren)

interface ProtectedIluminacionReportesChar91idChar93RouteRouteChildren {
  ProtectedIluminacionReportesChar91idChar93AreasRoute: typeof ProtectedIluminacionReportesChar91idChar93AreasRoute
  ProtectedIluminacionReportesChar91idChar93GeneralRoute: typeof ProtectedIluminacionReportesChar91idChar93GeneralRoute
  ProtectedIluminacionReportesChar91idChar93ResumenRoute: typeof ProtectedIluminacionReportesChar91idChar93ResumenRoute
}

const ProtectedIluminacionReportesChar91idChar93RouteRouteChildren: ProtectedIluminacionReportesChar91idChar93RouteRouteChildren =
  {
    ProtectedIluminacionReportesChar91idChar93AreasRoute:
      ProtectedIluminacionReportesChar91idChar93AreasRoute,
    ProtectedIluminacionReportesChar91idChar93GeneralRoute:
      ProtectedIluminacionReportesChar91idChar93GeneralRoute,
    ProtectedIluminacionReportesChar91idChar93ResumenRoute:
      ProtectedIluminacionReportesChar91idChar93ResumenRoute,
  }

const ProtectedIluminacionReportesChar91idChar93RouteRouteWithChildren =
  ProtectedIluminacionReportesChar91idChar93RouteRoute._addFileChildren(
    ProtectedIluminacionReportesChar91idChar93RouteRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedPerfilRouteRoute: typeof ProtectedPerfilRouteRouteWithChildren
  ProtectedSuscripcionRoute: typeof ProtectedSuscripcionRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedIluminacionIndexRoute: typeof ProtectedIluminacionIndexRoute
  ProtectedIluminacionReportesChar91idChar93RouteRoute: typeof ProtectedIluminacionReportesChar91idChar93RouteRouteWithChildren
  ProtectedIluminacionNuevoInformeIndexRoute: typeof ProtectedIluminacionNuevoInformeIndexRoute
  ProtectedIluminacionReportesIndexRoute: typeof ProtectedIluminacionReportesIndexRoute
  ProtectedIluminacionNuevoInformeAreasIndexRoute: typeof ProtectedIluminacionNuevoInformeAreasIndexRoute
  ProtectedIluminacionNuevoInformeOpinionIndexRoute: typeof ProtectedIluminacionNuevoInformeOpinionIndexRoute
  ProtectedIluminacionReportesPdfChar91idChar93IndexRoute: typeof ProtectedIluminacionReportesPdfChar91idChar93IndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedPerfilRouteRoute: ProtectedPerfilRouteRouteWithChildren,
  ProtectedSuscripcionRoute: ProtectedSuscripcionRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedIluminacionIndexRoute: ProtectedIluminacionIndexRoute,
  ProtectedIluminacionReportesChar91idChar93RouteRoute:
    ProtectedIluminacionReportesChar91idChar93RouteRouteWithChildren,
  ProtectedIluminacionNuevoInformeIndexRoute:
    ProtectedIluminacionNuevoInformeIndexRoute,
  ProtectedIluminacionReportesIndexRoute:
    ProtectedIluminacionReportesIndexRoute,
  ProtectedIluminacionNuevoInformeAreasIndexRoute:
    ProtectedIluminacionNuevoInformeAreasIndexRoute,
  ProtectedIluminacionNuevoInformeOpinionIndexRoute:
    ProtectedIluminacionNuevoInformeOpinionIndexRoute,
  ProtectedIluminacionReportesPdfChar91idChar93IndexRoute:
    ProtectedIluminacionReportesPdfChar91idChar93IndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  ApiUploadthingRoute: ApiUploadthingRoute,
  LoginIndexRoute: LoginIndexRoute,
  TestIndexRoute: TestIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
